import { z } from 'zod';
import { AgentRole } from './agent-role.enum';

// ---------------------------------------------------------------------------
// Zod schemas — single source of truth for InvokeRequest and related types.
// TypeScript types are derived via z.infer below.
// ---------------------------------------------------------------------------

/**
 * Schema for metadata describing the bootstrap context assembly produced by
 * the Message Broker. Enables downstream consumers (prompt rendering, logging)
 * to make budget-aware decisions without re-computing totals.
 */
export const bootstrapContextMetaSchema = z.object({
  /** Total number of context items included (project + conversation). */
  itemCount: z
    .number()
    .int()
    .min(0)
    .describe(
      'Total number of context items included (project + conversation)',
    ),
  /** Estimated token count consumed by the bootstrap payload. */
  estimatedTokens: z
    .number()
    .int()
    .min(0)
    .describe('Estimated token count consumed by the bootstrap payload'),
  /** Which scopes were queried during assembly. */
  scopesQueried: z
    .array(z.enum(['project', 'conversation']))
    .describe('Which scopes were queried during assembly'),
});

/**
 * Schema for context automatically assembled and injected by the Message
 * Broker before delivering an InvokeRequest to the target agent.
 *
 * Contains project-scope and conversation-scope items retrieved from the
 * Context Store. Agent-scope items are private working memory and are
 * intentionally excluded from bootstrap injection.
 */
export const bootstrapContextSchema = z.object({
  /** Project-scope context items (architectural decisions, tech stack, constraints). */
  project: z
    .record(z.string(), z.unknown())
    .describe(
      'Project-scope context items (architectural decisions, tech stack, constraints)',
    ),
  /** Conversation-scope context items for the current correlationId. Empty if no correlationId. */
  conversation: z
    .record(z.string(), z.unknown())
    .describe('Conversation-scope context items for the current correlationId'),
  /** Metadata about the bootstrap assembly. */
  meta: bootstrapContextMetaSchema.describe(
    'Metadata about the bootstrap assembly',
  ),
});

/**
 * Schema for a request to invoke an agent through the Message Broker.
 *
 * Created by any caller (including the moderator) and routed by the broker
 * to the target agent's handle method. The correlationId ties together every
 * hop in a delegation chain so that safeguards (circular call prevention,
 * depth limiting) and observability logs can trace the full call graph.
 */
export const invokeRequestSchema = z.object({
  /** Traces the entire call chain (UUID, generated by the originator). */
  correlationId: z
    .string()
    .describe(
      'Traces the entire call chain (UUID, generated by the originator)',
    ),
  /** Immediate caller's request ID, for nested-call debugging. */
  parentRequestId: z
    .string()
    .optional()
    .describe("Immediate caller's request ID, for nested-call debugging"),
  /** The role of the agent sending this request. */
  caller: z
    .nativeEnum(AgentRole)
    .describe('The role of the agent sending this request'),
  /** The role of the agent that should receive this request. */
  target: z
    .nativeEnum(AgentRole)
    .describe('The role of the agent that should receive this request'),
  /** What the target should do (natural-language task description). */
  action: z
    .string()
    .describe('What the target should do (natural-language task description)'),
  /** Optional key-value payload passed to the target agent. */
  context: z
    .record(z.string(), z.unknown())
    .optional()
    .describe('Optional key-value payload passed to the target agent'),
  /** Bootstrap context injected by the Message Broker (not set by callers). */
  bootstrapContext: bootstrapContextSchema
    .optional()
    .describe(
      'Bootstrap context injected by the Message Broker (not set by callers)',
    ),
  /** If true, caller blocks until the target responds; if false, fire-and-forget. */
  wait: z
    .boolean()
    .describe(
      'If true, caller blocks until the target responds; if false, fire-and-forget',
    ),
  /** Current call depth (0-based, incremented at each hop). */
  depth: z
    .number()
    .int()
    .min(0)
    .describe('Current call depth (0-based, incremented at each hop)'),
  /** Resume a prior SDK session instead of starting fresh. */
  sessionId: z
    .string()
    .optional()
    .describe('Resume a prior SDK session instead of starting fresh'),
});

// ---------------------------------------------------------------------------
// Inferred TypeScript types — derived from schemas, never hand-written.
// ---------------------------------------------------------------------------

/** Metadata about the bootstrap context assembly. */
export type BootstrapContextMeta = z.infer<typeof bootstrapContextMetaSchema>;

/** Context assembled and injected by the Message Broker before delivery. */
export type BootstrapContext = z.infer<typeof bootstrapContextSchema>;

/** A request to invoke an agent through the Message Broker. */
export type InvokeRequest = z.infer<typeof invokeRequestSchema>;

// ---------------------------------------------------------------------------
// InvokeResponse — plain interface (intentionally not schema-derived).
// Never parsed from external input; only constructed internally by the broker.
// ---------------------------------------------------------------------------

/**
 * The response returned by an agent after handling an InvokeRequest.
 *
 * Exactly one of `result` or `error` is populated depending on `success`.
 * The broker itself may also produce an `InvokeResponse` when a safeguard
 * rejects the request (depth exceeded, circular call, timeout, etc.).
 */
export interface InvokeResponse {
  /** Whether the invocation completed successfully. */
  success: boolean;
  /** Present on success — the agent's textual result. */
  result?: string;
  /** Present on failure — describes what went wrong. */
  error?: string;
  /** Total API cost in USD for this invocation. */
  totalCostUsd?: number;
  /** Wall-clock duration of the invocation in milliseconds. */
  durationMs?: number;
  /** SDK session ID — enables session resume on follow-up invocations. */
  sessionId?: string;
}
