import type { AgentRole } from './agent-role.enum';

/**
 * A request to invoke an agent through the Message Broker.
 *
 * Created by any caller (including the Terminal App's moderator) and routed
 * by the broker to the target agent's {@link AgentConnection.handle} method.
 * The `correlationId` ties together every hop in a delegation chain so that
 * safeguards (circular call prevention, depth limiting) and observability
 * logs can trace the full call graph.
 */
export interface InvokeRequest {
  /** Traces the entire call chain (UUID, generated by the originator). */
  correlationId: string;
  /** Immediate caller's request ID, for nested-call debugging. */
  parentRequestId?: string;
  /** The role of the agent sending this request. */
  caller: AgentRole;
  /** The role of the agent that should receive this request. */
  target: AgentRole;
  /** What the target should do (natural-language task description). */
  action: string;
  /** Optional key-value payload passed to the target agent. */
  context?: Record<string, unknown>;
  /** Bootstrap context injected by the Message Broker (not set by callers). */
  bootstrapContext?: BootstrapContext;
  /** If `true`, caller blocks until the target responds; if `false`, fire-and-forget. */
  wait: boolean;
  /** Current call depth (0-based, incremented at each hop). */
  depth: number;
  /** Resume a prior SDK session instead of starting fresh. */
  sessionId?: string;
}

/**
 * The response returned by an agent after handling an {@link InvokeRequest}.
 *
 * Exactly one of `result` or `error` is populated depending on `success`.
 * The broker itself may also produce an `InvokeResponse` when a safeguard
 * rejects the request (depth exceeded, circular call, timeout, etc.).
 */
export interface InvokeResponse {
  /** Whether the invocation completed successfully. */
  success: boolean;
  /** Present on success — the agent's textual result. */
  result?: string;
  /** Present on failure — describes what went wrong. */
  error?: string;
  /** Total API cost in USD for this invocation. */
  totalCostUsd?: number;
  /** Wall-clock duration of the invocation in milliseconds. */
  durationMs?: number;
  /** SDK session ID — enables session resume on follow-up invocations. */
  sessionId?: string;
}

/**
 * Context automatically assembled and injected by the Message Broker
 * before delivering an {@link InvokeRequest} to the target agent.
 *
 * Contains project-scope and conversation-scope items retrieved from the
 * Context Store. Agent-scope items are private working memory and are
 * intentionally excluded from bootstrap injection.
 */
export interface BootstrapContext {
  /** Project-scope context items (architectural decisions, tech stack, constraints). */
  project: Record<string, unknown>;
  /** Conversation-scope context items for the current correlationId. Empty if no correlationId. */
  conversation: Record<string, unknown>;
  /** Metadata about the bootstrap assembly. */
  meta: BootstrapContextMeta;
}

/**
 * Metadata describing the bootstrap context assembly produced by the
 * Message Broker. Enables downstream consumers (prompt rendering, logging)
 * to make budget-aware decisions without re-computing totals.
 */
export interface BootstrapContextMeta {
  /** Total number of context items included (project + conversation). */
  itemCount: number;
  /** Estimated token count consumed by the bootstrap payload. */
  estimatedTokens: number;
  /** Which scopes were queried during assembly. */
  scopesQueried: ('project' | 'conversation')[];
}
